/**
 * Release Note Service
 * Generates changelogs from resolved bugs and publishes draft GitHub releases.
 *
 * Uses Gemini to write professional, grouped, markdown changelog.
 * Falls back to template-based generation if Gemini unavailable.
 */

import { createDraftRelease } from "./github-service";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY ?? "";
const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";

async function callGemini(prompt: string, model = "gemini-2.0-flash"): Promise<string> {
  const res = await fetch(
    `${GEMINI_BASE}/models/${model}:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.3, maxOutputTokens: 2048 },
      }),
    }
  );
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const json = (await res.json()) as { candidates?: { content?: { parts?: { text?: string }[] } }[] };
  return json?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
}

export interface ResolvedBugSummary {
  id: number;
  title: string;
  component: string;
  severity: string;
  resolvedAt: Date | null;
  githubIssueId: string | null;
  githubIssueUrl: string | null;
}

// ─── Group bugs by component ───────────────────────────────────────────
function groupByComponent(bugs: ResolvedBugSummary[]): Record<string, ResolvedBugSummary[]> {
  return bugs.reduce((acc, bug) => {
    const key = bug.component || "other";
    if (!acc[key]) acc[key] = [];
    acc[key].push(bug);
    return acc;
  }, {} as Record<string, ResolvedBugSummary[]>);
}

// ─── Template-based changelog (fallback) ──────────────────────────────
function templateChangelog(bugs: ResolvedBugSummary[], tagName: string, days: number): string {
  const grouped = groupByComponent(bugs);
  const componentLabels: Record<string, string> = {
    auth: "🔐 Authentication",
    billing: "💳 Billing",
    ui: "🎨 UI / Frontend",
    api: "🔌 API",
    database: "🗄️ Database",
    notifications: "🔔 Notifications",
    other: "🔧 Other",
  };

  const sections = Object.entries(grouped)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([component, componentBugs]) => {
      const label = componentLabels[component] || `📦 ${component}`;
      const items = componentBugs.map((bug) => {
        const ghLink = bug.githubIssueId ? ` ([#${bug.githubIssueId}](${bug.githubIssueUrl}))` : "";
        const badge = bug.severity === "P0" ? " 🔴" : bug.severity === "P1" ? " 🟠" : "";
        return `- ${bug.title}${badge}${ghLink}`;
      });
      return `### ${label}\n${items.join("\n")}`;
    });

  return `# Release ${tagName}

> Covering the last ${days} day${days === 1 ? "" : "s"} — **${bugs.length} bug${bugs.length === 1 ? "" : "s"} resolved**

## 🐛 Bug Fixes

${sections.join("\n\n")}

---
*Generated by Bug Triage Max*`;
}

// ─── LLM-powered changelog ────────────────────────────────────────────
export async function generateChangelog(
  bugs: ResolvedBugSummary[],
  tagName: string,
  days: number
): Promise<string> {
  if (bugs.length === 0) {
    return `# Release ${tagName}\n\nNo bugs were resolved in the last ${days} day${days === 1 ? "" : "s"}.\n\n---\n*Generated by Bug Triage Max*`;
  }

  const apiKey = process.env.GEMINI_API_KEY ?? "";
  if (!apiKey) {
    console.log("[ReleaseNotes] No Gemini API key — using template fallback");
    return templateChangelog(bugs, tagName, days);
  }

  const bugList = bugs
    .map(
      (b) =>
        `- [${b.severity}] [${b.component}] ${b.title}${b.githubIssueId ? ` (GH #${b.githubIssueId})` : ""}`
    )
    .join("\n");

  const prompt = `You are a technical writer. Generate a professional GitHub release changelog in Markdown.

Release tag: ${tagName}
Period: Last ${days} days
Bugs resolved: ${bugs.length}

Bug list:
${bugList}

Instructions:
- Group by component (auth, billing, ui, api, database, notifications, other)
- Write a single clear sentence for each fix — concise, past tense
- Use appropriate emoji section headers (🐛 Bug Fixes, 🔐 Auth, 💳 Billing, 🎨 UI, etc.)
- For P0/P1 bugs, add a "[Critical]" or "[High]" prefix
- Add GitHub issue links where GH issue numbers are provided: "(#123)"
- End with a clean summary line
- Be professional, not too verbose
- Output ONLY the markdown, no explanation

Format:
# Release ${tagName}
> Brief one-line summary of this release

## 🐛 Bug Fixes

### [Section]
- Fix: ...

---
*Generated by Bug Triage Max*`;

  try {
    const result = await callGemini(prompt, "gemini-2.0-flash");
    if (result && result.trim().length > 50) {
      return result.trim();
    }
    throw new Error("Empty or too-short response from Gemini");
  } catch (err) {
    console.warn("[ReleaseNotes] Gemini failed, falling back to template:", err);
    return templateChangelog(bugs, tagName, days);
  }
}

// ─── Suggest a tag name ───────────────────────────────────────────────
export function suggestTagName(existingTags: string[]): string {
  const now = new Date();
  const base = `v${now.getFullYear()}.${String(now.getMonth() + 1).padStart(2, "0")}.${String(now.getDate()).padStart(2, "0")}`;

  if (!existingTags.includes(base)) return base;

  // If same-day release already exists, add suffix
  let i = 2;
  while (existingTags.includes(`${base}-${i}`)) i++;
  return `${base}-${i}`;
}

// ─── Publish to GitHub ────────────────────────────────────────────────
export async function publishToGitHub(params: {
  tagName: string;
  name: string;
  body: string;
}): Promise<{ id: number; url: string } | null> {
  return createDraftRelease(params);
}
